int randomNum();
int scrambler(char *);
inline bool spacePressed();
inline bool rPressed();
inline bool ePressed();
void doNothing();
void runTimer(char *);
void phaseTwo();
void printScramble(char *);
void phaseOne();